package com.ford.automation.driverFactory;

public enum Browser {
	FIRE_FOX, CHROME, SAFARI, INTERNET_EXPLORER,

	WINDOW_FIRE_FOX_LATEST, WINDOW_CHROME_LATEST, WINDOW_INTERNET_EXPLORER_LATEST,

	MAC_SAFARI_LATEST, MAC_FIRE_FOX_LATEST, MAC_CHROME_LATEST,

	IOS_IP5, IOS_IP6, IOS_IP6_PLUS, IOS_IPAD_AIR2,

	ANDROID_GALAXY_S5, ANDROID_GALAXY_S4, ANDROID_GALAXY_TAB_4,

	WINDOWS_EDGE

}
